### PR TITLE
Add a murmur hash function

### PR DESCRIPTION
**Pull request by wenweiP4**
Add a 64-bit murmur hash function that can hash arbitrary-length strings.

### CODE REVIEW

**Comment by wenweiP4** [comment]
> 1 change: let's name the function murmur_hash_32 to be clear that the result is 32-bit. This gives us room in the future to define a proper murmur_hash_64. Does that make sense?

Hi @apoliakov. There are two commits in the PR. The first returns int32. Then I did find an int64 version and it's in the 2nd commit. So the `murmur_hash` now returns int64. That said, do you want me to rename it to `murmur_hash_64`? 

>Note also: we can define it over other types (though string is most useful). Defining it over binary type could be handy in the future. We can deal with that separately.

Yes, I noticed the hash function takes void * and a length. So it can handle any data type. The question is the interface for scidb. Is it necessary to add similar lines for every scidb data type?
`REGISTER_FUNCTION(murmur_hash, list_of("string"), "int64", murmur_hash_string);`
`REGISTER_FUNCTION(murmur_hash, list_of("datetime"), "int64", murmur_hash_datetime);`
`...`

**Comment by wenweiP4** [comment]
There isn't too much online discussion on the issue of Murmur3 hash generating 128-bit instead of 64-bit. See these 3 options:

- Take the first 64-bits only, seen in Apache Hive Java port
  https://github.com/apache/hive/blob/master/storage-api/src/java/org/apache/hive/common/util/Murmur3.java
- Mix 2 uint64 into one uint64 in Google CityHash
  https://github.com/google/cityhash/blob/8af9b8c2b889d80c22d6bc26ba0df1afb79a30db/src/city.h#L101 
- Return 128-bit and leave it to the client code to decide, seen in Python `mmh3` module. https://github.com/veegee/mmh3/blob/master/mmh3module.cpp#L58


@apoliakov Which one do you think is the best for us?

**Comment by apoliakov** [comment]
Very cool findings!

I think using the 32-bit version is likely
 * the most well-tested and
 * sufficient for our purposes
So I think that's the safest bet because we can have confidence the authors
tested that path.
So this was the decision I made last time I dealt with this :)

The Google thing is interesting but is there a hidden bug there? Maybe,
maybe not. Harder to say.
You could try both - the 32 bit version and the google version - and then
test them in the field.

**Comment by wenweiP4** [comment]
Got it! Will add functions `murmur_hash_int32` and `murmur_city_hash_int64` accordingly.

**Comment by apoliakov** [comment]
Sounds good. Go ahead and push when ready. Thank you!

**Comment by wenweiP4** [comment]
Added `murmur_hash_32` and `murmur_city_hash_64` functions as planned.

**Comment by apoliakov** [comment]
Hey @wenweiP4 thank you! This is great. Feel free to merge it when you're ready.

**Pull request merged**
